name: Auto-Merge master to preprod

on:
  push:
    branches:
      - main

jobs:
  update-preprod:
    permissions: write-all
    name: Merge master into preprod
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'preprod'
          webhook_url: #if present add the Slack webhook
