name: Update cms/master

on:
  push:
    branches:
      - master

jobs:
  update-preprod:
    name: Merge main into preprod
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'preprod'
          webhook_url: #if present add the Slack webhook
