name: Auto-Merge sandbox to dev

on:
  push:
    branches:
      - sandbox

jobs:
  update-sandbox:
    permissions: write-all
    name: Merge sandbox into dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'sandbox'
          target: 'dev'
          webhook_url: #if present add the Slack webhook
