name: Auto-Merge preprod to sandbox

on:
  push:
    branches:
      - preprod

jobs:
  update-sandbox:
    permissions: write-all
    name: Merge preprod into sandbox
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'preprod'
          target: 'sandbox'
          webhook_url: #if present add the Slack webhook
